version: '3'
services:
  redis: 
    image: redis:latest
    container_name: my-redis
    restart: always
    ports:
      - 6380:6379
    environment:
      - REDIS_PASSWORD=mypassword
    command: ["redis-server", "--requirepass", "mypassword"]

  app:
    build: .
    container_name: urlShortner
    restart: always
    ports:
      - 3000:5000
    environment:
      - REDIS_PORT=6380
      - REDIS_HOST=my-redis
      - REDIS_PASSWORD=mypassword

    
  
