version: '3.8'
services:
  redis: 
    image: redis:latest
    container_name: my-redis
    restart: always
    ports:
      - "6380:6379"
    environment:
      - REDIS_PASSWORD=mypassword
    command: ["redis-server", "--requirepass", "mypassword"]

  app:
    build: .
    container_name: urlShortner
    restart: always
    ports:
      - "8080:5000"
    depends_on:
      - redis
    environment:
      - REDIS_PORT=6379  # Keep this as 6379 since the app is inside the network
      - REDIS_HOST=my-redis
      - REDIS_PASSWORD=mypassword
      - PORT=8080
