version: '3'
services:
  redis: 
    image: redis:latest
    container_name: my-redis
    restart: always
    ports:
      - 6380:6379
    environment:
      - REDIS_PASSWORD=mypassword
    command: ["redis-server", "--requirepass", "mypassword"]
    
  